cortex-lab/phy

CONTRIBUTE.md
Would probably benefit from @nippoo's proof-reading. :)
=> Update CONTRIBUTE document

phy/cluster/manual/clustering.py, phy/plot/waveforms.py, phy/utils/_color.py, phy/utils/array.py, phy/utils/tests/test_array.py, phy/utils/tests/test_color.py
=> A few updates in waveform view

.travis.yml
IPython 3.0 now released on conda: we can use this!
=> Use release rather than beta version of IPython

phy/cluster/manual/tests/test_wizard.py, phy/cluster/manual/wizard.py
=> most_similar_clusters now accepts a default cluster argument

phy/cluster/manual/session.py, phy/cluster/manual/store.py, phy/cluster/manual/tests/test_session.py, phy/cluster/manual/tests/test_store.py, phy/electrode/mea.py, phy/io/kwik_model.py, phy/io/mock/artificial.py
=> Improve cluster store

phy/cluster/manual/_utils.py, phy/cluster/manual/cluster_metadata.py, phy/cluster/manual/clustering.py, phy/cluster/manual/selector.py, phy/cluster/manual/session.py, phy/cluster/manual/store.py, phy/cluster/manual/tests/test_clustering.py, phy/cluster/manual/tests/test_selector.py, phy/cluster/manual/tests/test_session.py, phy/cluster/manual/tests/test_store.py, phy/cluster/manual/tests/test_utils.py, phy/cluster/manual/tests/test_view_model.py, phy/cluster/manual/tests/test_wizard.py, phy/cluster/manual/view_model.py, phy/cluster/manual/wizard.py, phy/electrode/mea.py, phy/electrode/tests/test_mea.py, phy/io/h5.py, phy/io/kwik_model.py, phy/io/mock/artificial.py, phy/io/mock/kwik.py, phy/io/mock/tests/test_artificial.py, phy/io/tests/test_kwik_model.py, phy/plot/features.py, phy/plot/tests/test_waveforms.py, phy/plot/waveforms.py, phy/utils/event.py, phy/utils/testing.py, phy/utils/tests/test_event.py
Ready for review.
* Closes #144
* Closes #145
* Closes #162
* Closes #172 
* Closes #173
* Closes #179
* Closes #180 
* Closes #181
* Closes #184
* Closes #185
* Closes #188
=> Fixes and updates in Kwik model

phy/cluster/manual/tests/test_session.py, phy/io/h5.py, phy/io/kwik_model.py, phy/io/mock/kwik.py, phy/io/tests/test_h5.py, phy/io/tests/test_kwik_model.py
```python
session.model.add_clustering(name, spike_clusters)
session.model.rename_clustering(old_name, new_name)
session.model.copy_clustering(name, new_name)
session.model.delete_clustering(name)
```
* Closes #192
* Closes #209
=> Manage multiple clusterings

.gitignore, Dockerfile, Makefile, phy/__init__.py, phy/scripts/tests/test_phy_script.py, pytest.ini, tools/release.py
Some automatic release tools. It's not completely done nor ideal but it's ready to merge: we can improve later, and I have some work to do before any release anyway...
Another PR will be uploaded once this one is merged.
=> [MRG] Release tools

phy/io/kwik/store_items.py
=> [MRG] Fixed bug when computing mean features after undo

phy/io/h5.py
=> [MRG] Fix h5error

phy/plot/features.py
=> [MRG] Fixed float division bug with time in feature view.

.gitignore, .travis.yml, Makefile, phy/cluster/algorithms.py, phy/cluster/default_settings.py, phy/cluster/manual/gui.py, phy/cluster/tests/test_algorithms.py, phy/cluster/view_models.py, phy/gui/base.py, phy/gui/dock.py, phy/gui/qt.py, phy/gui/tests/test_base.py, phy/io/base.py, phy/io/h5.py, phy/io/kwik/creator.py, phy/plot/features.py, phy/plot/glsl/waveforms.vert, phy/plot/tests/test_features.py, phy/utils/array.py, phy/utils/settings.py, phy/utils/tests/test_settings.py, requirements-dev.txt, setup.cfg, setup.py
* Various bug fixes
* Better handling of dictionary settings
* Snippet commands
* Closes #216
* Closes #355
* Closes #358
* Closes #375
* Closes #393
* Closes #395
=> [MRG] Bug fixes

phy/io/kwik/store_items.py
This fix returns the center of mass in the "y" dimension.
Closes #440
=> Fixing the mean_probe_position element in store

.travis.yml, README.md, requirements-dev.txt
seems better than coveralls @nippoo ...
=> [MRG] Replace coveralls by codecov 

phy/io/kwik/creator.py, phy/utils/array.py
=> [MRG] Fix bug with multiple dat files in spike detection

phy/__init__.py, phy/plot/_vispy_utils.py, phy/utils/datasets.py, setup.py, tools/api.py
=> [MRG] Fix doc tools

.travis.yml, CONTRIBUTE.md, phy/io/store.py, phy/plot/traces.py, phy/plot/waveforms.py, phy/utils/_misc.py, phy/utils/settings.py, phy/utils/tests/test_misc.py, setup.py
* Closes #484.
* Drop Python 3.3 support, because of a bug on travis with bytes, string, and encodings...
=> [MRG] Use JSON for internal settings

MANIFEST.in
Fix bug with `phy/gui/static/*.html` files not installed.
=> [MRG] Add phy/gui/static files

phy/cluster/session.py, phy/cluster/tests/test_algorithms.py, phy/traces/detect.py, phy/traces/tests/test_detect.py
=> [MRG] Fix multiple thresholds

phy/cluster/session.py, phy/scripts/phy_script.py
=> [MRG] Fix `phy cluster-auto`  command

phy/cluster/default_settings.py, phy/cluster/manual/gui.py, phy/cluster/session.py, phy/electrode/__init__.py, phy/electrode/mea.py, phy/gui/base.py, phy/io/base.py, phy/io/kwik/creator.py, phy/io/kwik/model.py, phy/io/kwik/store_items.py, phy/io/kwik/tests/test_store_items.py, phy/plot/waveforms.py, phy/scripts/phy_script.py, phy/traces/__init__.py, phy/traces/waveform.py
Minor fixes for template matching conversion script.
Closes #301
=> [MRG] Tweaks for template to Kwik conversion script

appveyor.yml
=> [MRG] Appveyor

README.md
=> [MRG] Add some badges in README

phy/cluster/tests/test_algorithms.py, phy/cluster/tests/test_session.py, phy/cluster/tests/test_view_models.py, phy/conftest.py, phy/gui/tests/test_base.py, phy/io/kwik/tests/test_creator.py, phy/io/kwik/tests/test_mock.py, phy/io/kwik/tests/test_model.py, phy/io/kwik/tests/test_store_items.py, phy/io/tests/test_h5.py, phy/io/tests/test_sparse.py, phy/io/tests/test_store.py, phy/io/tests/test_traces.py, phy/scripts/tests/test_phy_script.py, phy/utils/tempdir.py, phy/utils/tests/test_array.py, phy/utils/tests/test_datasets.py, phy/utils/tests/test_misc.py, phy/utils/tests/test_settings.py
Use pytest's fixture mechanism with a global `tempdir` fixture defined in `conftest.py`.
=> [MRG] Refactor tempdir in testing suite

phy/scripts/phy_script.py, tests/scripts/test_phy_spikesort.py
The integration test has been removed -- it needs to be rewritten (generate a PRM instead of a KWIK).
=> [MRG] Fixed bug in phy script

.gitignore, conftest.py, phy/detect/tests/test_spikedetekt.py, phy/scripts/tests/test_phy_script.py, phy/utils/datasets.py, phy/utils/tests/test_datasets.py
* Closes #506
* Closes #510
* Closes #529
=> [MRG] Improve datasets module

phy/io/kwik/model.py
=> [MRG] Do not crash if the .dat file is not present

phy/session/session.py
=> [MRG] Fix clustering bugs in detect and cluster functions

phy/scripts/phy_script.py, tests/scripts/test_phy_spikesort.py
=> [MRG] Make consistent the interval option in phy traces

phy/scripts/phy_script.py, tests/scripts/test_phy_spikesort.py
=> [MRG] Fix cluster-auto from PRM file

phy/session/session.py, phy/session/tests/test_session.py
=> [MRG] Save KK2 current clustering in text file

phy/cluster/manual/view_models.py, phy/scripts/phy_script.py, phy/session/session.py
=> [MRG] Add channel-group option phy cluster-manual

phy/detect/spikedetekt.py
This closes #577 - properly rebased against master. Tests should now pass.
=> [MRG] Fixed bug when using --interval that doesn't start at zero

phy/cluster/manual/tests/test_gui.py, phy/cluster/manual/wizard.py
=> [MRG] Fix wizard when moving closest match cluster to group

Makefile, setup.py
=> [MRG] Expanded pytest setup.py / Makefile framework. Closes #543

phy/cluster/manual/gui.py
=> fixed bug #594

phy/scripts/phy_script.py, phy/session/session.py, tests/scripts/test_phy_spikesort.py
=> [MRG] Add channel group parameter in cluster auto function

phy/plot/_vispy_utils.py
=> Remove dependency to VisPy Visual base class

phy/io/kwik/creator.py
There doesn't appear to be an easy fix currently -- better to do the formatless refactoring before fixing this.
=> [MRG] No support for multiple .dat files yet

phy/io/kwik/creator.py
=> [MRG] Write __version_git__ to each new kwik

phy/cluster/manual/controller.py, phy/cluster/manual/tests/test_views.py, phy/cluster/manual/views.py, phy/plot/utils.py
* Add margin between boxes in waveform view
* Do not reinitialize the zoom when toggling show_labels with autozoom enabled
=> Minor plot improvements

phy/gui/actions.py
Update to #696, I didn't know how to merge with the existing pull request. This has the same modification, but with handling of the defaults and arguments supplied to the partial (#696 works when the arguments supplied to the partial also have defaults).
Fixes #695
=> Deal with partial functions when used as wrapped callbacks.

phy/cluster/manual/gui_component.py, phy/cluster/manual/tests/test_gui_component.py, phy/gui/actions.py
=> Update _wrap_callback_args to handle the no-default-arguments case.

phy/cluster/manual/controller.py
Traces are now normalized on the fly in the trace view.
=> Fix trace normalization in trace view

phy/cluster/manual/gui_component.py, phy/cluster/manual/tests/test_gui_component.py
Closes https://github.com/kwikteam/phy-contrib/issues/59
=> Fix move action dialog

README.md
=> Add links to user documentation

phy/cluster/manual/controller.py, phy/cluster/manual/tests/conftest.py, phy/cluster/manual/views.py
=> Display traces in vertical channel order in trace view

.travis.yml, phy/cluster/manual/_utils.py, phy/cluster/manual/controller.py, phy/cluster/manual/gui_component.py, phy/cluster/manual/tests/test_controller.py, phy/cluster/manual/tests/test_gui_component.py, phy/cluster/manual/tests/test_utils.py, phy/cluster/manual/views.py, phy/gui/qt.py, phy/gui/static/table.js, phy/gui/tests/test_widgets.py, phy/gui/widgets.py, setup.cfg
*  Improve selection of next cluster after merge and move
* Add `label` action in `ManualClustering`
* Fixes kwikteam/phy-contrib#38
* Fixes kwikteam/phy-contrib#70
=> Improve manual clustering component

phy/apps/base.py
Fixes a bug where selected clusters were being shown in the grey dots/histogram ('other' clusters)
=> Fix bug where selected clusters were being shown in the grey

phy/plot/gloo/variable.py
NumPy versions >1.24 will no longer work with code including np.bool rather than issue a warning. So I just changed np.bool to np.bool_ which should work for new and older versions of NumPy.
=> Update variable.py to. use np.bool_ rather than deprecated np.bool

README.md, environment.yml, phy/__init__.py, phy/utils/plugin.py, requirements.txt
@AceTylerCholine could you test this?
If this doesn't work I'll need to do more extensive testing (on Friday) to get this working.
=> Fix for plugins
