- .travis.yml
- Makefile
- phy/io/tests/test_h5.py
Main advantages over nose:
* assertions errors are reported with details on the assertion
* it is much easier to assert raised exceptions, using a `with` statement
Closes #28.
> Switching from nose to py.test

- .travis.yml
- phy/cluster/manual/session.py
- phy/datasets/mock.py
- phy/electrode/mea.py
- phy/electrode/tests/test_mea.py
- phy/io/h5.py
- phy/io/kwik_model.py
- phy/io/tests/test_kwik_model.py
- phy/plot/tests/test_waveforms.py
- phy/plot/waveforms.py
- phy/utils/array.py
- phy/utils/tests/test_array.py
- phy/waveform/filter.py
- phy/waveform/loader.py
- phy/waveform/tests/test_filter.py
- phy/waveform/tests/test_loader.py
> Fix bugs for the first Kwik prototype

- phy/cluster/manual/cluster_info.py
- phy/cluster/manual/interface.py
- phy/cluster/manual/tests/test_cluster_info.py
- phy/io/h5.py
- phy/io/kwik_model.py
- phy/io/mock/artificial.py
- phy/plot/tests/test_waveforms.py
- phy/plot/waveforms.py
* Use uint8 textures instead of float32 for better compatibility
* Added old KlustaViewa colormap
* Renamed `field` to `default` in cluster metadata decorator
* Load cluster metadata in kwik
* Added backend option in the interface for VisPy
> Make WaveformView work in WebGL

- phy/io/kwik/creator.py
- phy/scripts/phy_script.py
* Built-in PRB files can now be specified by their names from the PRM file.
* `--pdb` CLI argument to activate the IPython debugger in post-mortem mode.
> [WIP] Tweaks for quick start

- phy/cluster/algorithms.py
- phy/cluster/session.py
- phy/cluster/tests/test_session.py
Closes #501.
@nsteinme this saves the latest KK2 iteration in a new clustering name `kk2_current`. Due to a limitation in the file format (another one), the current active clustering cannot be changed, and it is just simpler to save it in a separate clustering.
The `KwikModel` implements several methods to manage different clusterings in the same `.kwik` file (add, remove, copy, rename, etc.).
> [MRG] Save KK2 iteration

- phy/utils/_misc.py
Fixing this error:
```
19:56:30 [W] Error when loading `/Users/shabnamkadir/globalphy/simple_data/test_hybrid_120sec.phy/cluster_store/0/main/waveforms_spikes`: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte.
---------------------------------------------------------------------------
BufferError                               Traceback (most recent call last)
<ipython-input-6-f9aba4144653> in <module>()
1 model = KwikModel(kwik_path)
----> 2 session = Session(kwik_path)
/Users/shabnamkadir/globalphy/phy/phy/cluster/session.py in __init__(self, kwik_path, clustering, model, use_store, phy_user_dir, waveform_filter)
83                                       default_settings_path=settings_path,
84                                       vm_classes=self._vm_classes,
---> …
```
> Fix contiguous bug.

- tools/api.py
Function headers are no longer enclosed by backticks (code)
> Updates in API doc generator

- phy/io/kwik/model.py
- phy/io/traces.py
Closes #602 
Closes #592 
Closes #590 
Finally fixes #488 and #437 properly!
Traces-opening logic is now (as per docstring)
> The `.kwik` and `.kwx` must be in the same folder with the same basename.
> The files containing the traces (`.raw.kwd` or `.dat` / `.bin`) are determined according to the following logic:
> - Is there a path specified to a file which exists in [KWIK]/recordings/[X]/raw? If so, open it.
> - If this file does not exist, does a file exist with the same name in the current directory? If so, open it.
> - If such a file does not exist, or no filename is specified in the [KWIK], then is there a `raw.kwd` with the experiment basename in the current directory? If so, open it.
> - If not, return with a warning.
> [MRG] Better handling of traces

- phy/scripts/phy_script.py
The main parser's defaults overwrite the subparser so `func` is None on some systems (why this doesn't happen everywhere, I have no idea).
> [MRG] Fix issue #465

- phy/io/kwik/model.py
- phy/session/session.py
* Fixes #581 
* Fixes #620
Note that when showing a GUI with a new clustering/shank you need to use `session.show_gui()` to create and load a new GUI rather than `gui.show()` which will try and show the old one with disastrous results...
> [MRG] fix #581 and fix #620

- phy/__init__.py
- phy/utils/cli.py
- phy/utils/testing.py
Particularly useful during development and debugging
* `--pdb`: enable the IPython debugger
* `--ipython`: enable interactive IPython with the GUI
* `--prof`: profiler (saved in `.profile/stats.txt`)
* `--lprof`: line profiler (saved in `.profile/stats.txt`), need to specify profiled function with `@profile` decorator in the code
> CLI enhancements

- phy/io/context.py
- phy/io/tests/test_context.py
memcache is now faster, but it requires function arguments to be hashable (**no ndarrays**). Typically, this is used for `cluster_id => value` functions so this is okay.
There should be performance improvements when a memcached function is called many times with different arguments (example of the similarity function). Previously, the bottleneck was the computation of the hash of the function's arguments (using joblib's `hash()` function, which is overkill unless using ndarrays)
> Faster memcache that requires hashable arguments

- phy/cluster/manual/views.py
I've noticed two issues with the FeatureView labels, which make things very confusing for a new user:
1. Most of the labels are missing along the left edge of the subplots.
2. The label value in the bottom right corner is wrong.
This separates setting the FeatureView labels from the (iterated) plotting commands, gets rid of a hack, and fixes the two issues above. This is a rather quick and naive stab at the code, but it seems to work.
Here is what it looks like before the fix:
And here is what it looks like after:
> Factor out and fix plotting of FeatureView labels

- phy/cluster/manual/controller.py
This is disabled only in the Kwik GUI where there aren't too many channels.
> Disable showing unmasked-only waveforms

- phy/cluster/views/correlogram.py
this fixes https://github.com/kwikteam/phy/issues/813 in the gloo branch
Without the `prompt=True` the window to change bin size and window size doesn't show
Cheers
Alessio
> Fix bug in correlograms actions

- phy/gui/state.py
In Windows, `op.exists`, `_ensure_dir_exists`, `_load_json` and `save_json` can fail since `WindowsPath` are not handled by os. 
I just addeed a parse into `str` to the pathlib object when tose functions are called. This solves our problems in running phy on windows.
> Calls to exists, load_json, save_json parse Path objects to str

- phy/apps/template/gui.py
- phy/plot/gloo/parser.py
- phy/plot/gloo/shader.py
- phy/plot/visuals.py
- phy/utils/context.py
`WindowsPath` raise errors in windows when `os` calls are performed. Instead they work for `PosixPath`.
Running the newest phy version I hade to make these changes to make it run.
> Force str() to os and open calls for Windows

- phy/cluster/supervisor.py
Reverting a split with 'undo' results in an error if there is another split in the history with the same number of spike IDs. (Granted, that doesn't happen very often.)
```bash
11:08:24.429 [W] actions:213          Error when executing action Undo.
11:08:24.430 [D] actions:214          Traceback (most recent call last):
File "/xxxxxxx/phy/gui/actions.py", line 211, in wrapped
return callback(*args)
File "/xxxxxxx/phylib/utils/event.py", line 141, in emit
res.append(f(sender, *args, **kwargs))
File "/xxxxxxx/phy/cluster/supervisor.py", line 851, in _on_action
self.task_logger.process()
File "/xxxxxxx/phy/cluster/supervisor.py", line 127, in process
self._eval(task)
File "/xxxxxxx/phy/cluster/supervisor.py", line 116, in _eval
f(*args, **kwargs)
File "/xxxxxxx/phy/cluster/supervisor.py", …
```
> Fix rare error on undo

- phy/utils/plugin.py
When using a custom plugin folder which is version controlled by git, phy recurses into all the subfolders which is unneccessary. This PR excludes paths with `.git` when phy is searching plugins in plugin.py
```
14:59:22.415 [D] plugin:74            Scanning `/home/ycan/repos/phy_plugins/.git`.
14:59:22.415 [D] plugin:74            Scanning `/home/ycan/repos/phy_plugins/.git/objects/77`.
14:59:22.415 [D] plugin:74            Scanning `/home/ycan/repos/phy_plugins/.git/objects/7a`.
14:59:22.415 [D] plugin:74            Scanning `/home/ycan/repos/phy_plugins/.git/objects/62`.
14:59:22.416 [D] plugin:74            Scanning `/home/ycan/repos/phy_plugins/.git/objects/47`.
14:59:22.416 [D] plugin:74            Scanning `/home/ycan/repos/phy_plugins/.git/objects/d0`.
14:59:22.416 [D] plugin:74 …
```
> Do not recurse into .git when looking for plugins

- phy/gui/static/styles.css
- phy/gui/widgets.py
table headers disappeared when scrolling in clusterView
Added sticky css position to table th
Had to remove high-dpi transformations in widgets.py because interfered with 'stickiness' property; trade-off necessitates setting a larger font-size with plugin.
> Added sticky headers to clusterView & similarityView tables

- phy/cluster/supervisor.py
- phy/gui/qt.py
This PR addresses and may resolve #1143, resolve #1151, resolve #1156, resolve #1159, and resolve #1165.
As @FranciscoNaveros and others have [observed](https://github.com/cortex-lab/phy/issues/1159#issue-1239068482), the issue of blank cluster views occurs when the number of clusters or columns exceeds a certain limit. This seems to be due to the method `setHtml` of `QWebEnginePage` having a [size limit of 2 MB](https://doc.qt.io/qtforpython-5/PySide2/QtWebEngineWidgets/QWebEnginePage.html?highlight=qwebenginepage#PySide2.QtWebEngineWidgets.PySide2.QtWebEngineWidgets.QWebEnginePage.setHtml) for the HTML code to load.
The proposed fix here simply stores the HTML code to a temporary file and uses the method `setUrl` instead. The temporary files are cleared appropriately (when new HTML is …
> Set cluster views from URL of local file

- environment.yml
@rossant Welcome back!
I saw in the issues that some people were using the `environment.yml` file for install, so people don't use the yaml file with wrong versions I updated that.
In short I added all the dependencies you listed. Fixed the sklearn->scikit-learn and had it pull from git instead of pypi.
I just tested creating a conda env with 
`conda env create --file environment.yml`
and it worked fine on my computer.
> updated environment.yml so people can also install env with that

- phy/apps/base.py
- phy/cluster/clustering.py
- phy/cluster/tests/test_clustering.py
@rossant 
Just an FYI that `np.in1d` will be deprecated with the next version of NumPy and I assume will eventually be a hard error. This just updates calls to `np.in1d` to `np.isin`, which is the the NumPy standard. I also opened a PR in `phylib` to do the same.
I also scanned both repos for some other hard errors coming like `float_` `NaN` and `Inf` which are aliases which will be dropped in the next version of NumPy (recs are to use `float64` `nan` and `inf`, which both repos already use where necessary).
> Replace `np.in1d` which will be deprecated

- phy/utils/plugin.py
@rossant,
I don't actually have the phy test suite setup so I made this fix based on reading python docs. In Python 3.12 they have completely removed `imp` and the rec is to switch to `importlib`. Could you either test to make sure these changes work or walk me through setting up the phy test suite so I can make sure this works. 
If you don't want to do this I'll do a PR to change the python version to < 3.11 for the install stuff.
> Fix removal of imp in python 3.12
